// Sales Summary :
export const SALES_SUMMARY_REQUEST = 'SALES_SUMMARY_REQUEST';
export const SALES_SUMMARY_SUCCESS = 'SALES_SUMMARY_SUCCESS';
export const SALES_SUMMARY_FAILURE = 'SALES_SUMMARY_FAILURE';

// sales by item category :
export const SALES_BY_ITEM_CATEGORY_REQUEST = 'SALES_BY_ITEM_CATEGORY_REQUEST';
export const SALES_BY_ITEM_CATEGORY_SUCCESS = 'SALES_BY_ITEM_CATEGORY_SUCCESS';
export const SALES_BY_ITEM_CATEGORY_FAILURE = 'SALES_BY_ITEM_CATEGORY_FAILURE';

//sales by revenue class :
export const SALES_BY_REVENUE_CLASS_REQUEST = 'SALES_BY_REVENUE_CLASS_REQUEST';
export const SALES_BY_REVENUE_CLASS_SUCCESS = 'SALES_BY_REVENUE_CLASS_SUCCESS';
export const SALES_BY_REVENUE_CLASS_FAILURE = 'SALES_BY_REVENUE_CLASS_FAILURE';

// actual sales Maghil :
export const ACTUAL_SALES_REQUEST = 'ACTUAL_SALES_REQUEST';
export const ACTUAL_SALES_SUCCESS = 'ACTUAL_SALES_SUCCESS';
export const ACTUAL_SALES_FAILURE = 'ACTUAL_SALES_FAILURE';

// actual sales third party :
export const ACTUAL_SALES_THIRD_PARTY_REQUEST = 'ACTUAL_SALES_THIRD_PARTY_REQUEST';
export const ACTUAL_SALES_THIRD_PARTY_SUCCESS = 'ACTUAL_SALES_THIRD_PARTY_SUCCESS';
export const ACTUAL_SALES_THIRD_PARTY_FAILURE = 'ACTUAL_SALES_THIRD_PARTY_FAILURE';