// Sales Summary :
export const SALES_SUMMARY_REQUEST = 'SALES_SUMMARY_REQUEST';
export const SALES_SUMMARY_SUCCESS = 'SALES_SUMMARY_SUCCESS';
export const SALES_SUMMARY_FAILURE = 'SALES_SUMMARY_FAILURE';

// sales by item category :
export const SALES_BY_ITEM_CATEGORY_REQUEST = 'SALES_BY_ITEM_CATEGORY_REQUEST';
export const SALES_BY_ITEM_CATEGORY_SUCCESS = 'SALES_BY_ITEM_CATEGORY_SUCCESS';
export const SALES_BY_ITEM_CATEGORY_FAILURE = 'SALES_BY_ITEM_CATEGORY_FAILURE';

//sales by revenue class :
export const SALES_BY_REVENUE_CLASS_REQUEST = 'SALES_BY_REVENUE_CLASS_REQUEST';
export const SALES_BY_REVENUE_CLASS_SUCCESS = 'SALES_BY_REVENUE_CLASS_SUCCESS';
export const SALES_BY_REVENUE_CLASS_FAILURE = 'SALES_BY_REVENUE_CLASS_FAILURE';

// actual sales Maghil :
export const ACTUAL_SALES_REQUEST = 'ACTUAL_SALES_REQUEST';
export const ACTUAL_SALES_SUCCESS = 'ACTUAL_SALES_SUCCESS';
export const ACTUAL_SALES_FAILURE = 'ACTUAL_SALES_FAILURE';

// actual sales third party :
export const ACTUAL_SALES_THIRD_PARTY_REQUEST = 'ACTUAL_SALES_THIRD_PARTY_REQUEST';
export const ACTUAL_SALES_THIRD_PARTY_SUCCESS = 'ACTUAL_SALES_THIRD_PARTY_SUCCESS';
export const ACTUAL_SALES_THIRD_PARTY_FAILURE = 'ACTUAL_SALES_THIRD_PARTY_FAILURE';

//Hourly sales :
export const HOURLY_SALES_REQUEST = 'HOURLY_SALES_REQUEST';
export const HOURLY_SALES_SUCCESS = 'HOURLY_SALES_SUCCESS';
export const HOURLY_SALES_FAILURE = 'HOURLY_SALES_FAILURE';

// Live discount :
export const LIVE_DISCOUNT_REQUEST = 'LIVE_DISCOUNT_REQUEST';
export const LIVE_DISOUNT_SUCCESS = 'LIVE_DISOUNT_SUCCESS';
export const LIVE_DISCOUNT_FAILURE = 'LIVE_DISCOUNT_FAILURE';

// Open Sales :
export const LIVE_OPEN_SALES_REQUEST = 'LIVE_OPEN_SALES_REQUEST';
export const LIVE_OPEN_SALES_SUCCESS = 'LIVE_OPEN_SALES_SUCCESS';
export const LIVE_OPEN_SALES_FAILURE = 'LIVE_OPEN_SALES_FAILURE';

// live orders :
export const LIVE_ORDERS_REQUEST = 'LIVE_ORDERS_REQUEST';
export const LIVE_ORDERS_SUCCESS = 'LIVE_ORDERS_SUCCESS';
export const LIVE_ORDERS_FAILURE = 'LIVE_ORDERS_FAILURE';

// live refunds :
export const LIVE_REFUNDS_REQUEST = 'LIVE_REFUNDS_REQUEST';
export const LIVE_REFUNDS_SUCCESS = 'LIVE_REFUNDS_SUCCESS';
export const LIVE_REFUNDS_FAILURE = 'LIVE_REFUNDS_FAILURE';

//  net sales :
export const LIVE_NET_SALES_REQUEST = 'LIVE_NET_SALES_REQUEST'
export const LIVE_NET_SALES_SUCCESS = 'LIVE_NET_SALES_SUCCESS'
export const LIVE_NET_SALES_FAILURE = 'LIVE_NET_SALES_FAILURE'

// live order non dine in :
export const LIVE_ORDER_NON_DINE_IN_REQUEST = 'LIVE_ORDER_NON_DINE_IN_REQUEST'
export const LIVE_ORDER_NON_DINE_IN_SUCCESS = 'LIVE_ORDER_NON_DINE_IN_SUCCESS'
export const LIVE_ORDER_NON_DINE_IN_FAILURE = 'LIVE_ORDER_NON_DINE_IN_FAILURE'

// discuount summary :
export const DISCOUNT_SUMMARY_REQUEST = 'DISCOUNT_SUMMARY_REQUEST';
export const DISCOUNT_SUMMARY_SUCCESS = 'DISCOUNT_SUMMARY_SUCCESS';
export const DISCOUNT_SUMMARY_FAILURE = 'DISCOUNT_SUMMARY_FAILURE';

// cancellation summary :
export const CANCELLATION_SUMMARY_REQUEST = 'CANCELLATION_SUMMARY_REQUEST'
export const CANCELLATION_SUMMARY_SUCCESS = 'CANCELLATION_SUMMARY_SUCCESS'
export const CANCELLATION_SUMMARY_FAILURE = 'CANCELLATION_SUMMARY_FAILURE'

// employee staff tip gratuity :
export const EMPLOYEE_STAFF_TIP_GRATUITY_REQUEST = 'EMPLOYEE_STAFF_TIP_GRATUITY_REQUEST'
export const EMPLOYEE_STAFF_TIP_GRATUITY_SUCCESS = 'EMPLOYEE_STAFF_TIP_GRATUITY_SUCCESS'
export const EMPLOYEE_STAFF_TIP_GRATUITY_FAILURE = 'EMPLOYEE_STAFF_TIP_GRATUITY_FAILURE'

// employee staff discount :
export const EMPLOYEE_STAFF_DISCOUNT_REQUEST = 'EMPLOYEE_STAFF_DISCOUNT_REQUEST'
export const EMPLOYEE_STAFF_DISCOUNT_SUCCESS = 'EMPLOYEE_STAFF_DISCOUNT_SUCCESS'
export const EMPLOYEE_STAFF_DISCOUNT_FAILURE = 'EMPLOYEE_STAFF_DISCOUNT_FAILURE'

// employee staff performance :
export const EMPLOYEE_STAFF_PERFORMANCE_REQUEST = 'EMPLOYEE_STAFF_PERFORMANCE_REQUEST'
export const EMPLOYEE_STAFF_PERFORMANCE_SUCCESS = 'EMPLOYEE_STAFF_PERFORMANCE_SUCCESS'
export const EMPLOYEE_STAFF_PERFORMANCE_FAILURE = 'EMPLOYEE_STAFF_PERFORMANCE_FAILURE'

// employee staff activity :
export const EMPLOYEE_STAFF_ACTIVITY_REQUEST = 'EMPLOYEE_STAFF_ACTIVITY_REQUEST'
export const EMPLOYEE_STAFF_ACTIVITY_SUCCESS = 'EMPLOYEE_STAFF_ACTIVITY_SUCCESS'
export const EMPLOYEE_STAFF_ACTIVITY_FAILURE = 'EMPLOYEE_STAFF_ACTIVITY_FAILURE'

// day checkIn :
export const DAY_CHECKIN_REQUEST = 'DAY_CHECKIN_REQUEST'
export const DAY_CHECKIN_SUCCESS = 'DAY_CHECKIN_SUCCESS'
export const DAY_CHECKIN_FAILURE = 'DAY_CHECKIN_FAILURE'

// daily checkIn :
export const DAILY_CHECKIN_REQUEST = 'DAILY_CHECKIN_REQUEST'
export const DAILY_CHECKIN_SUCCESS = 'DAILY_CHECKIN_SUCCESS'
export const DAILY_CHECKIN_FAILURE = 'DAILY_CHECKIN_FAILURE'

// daily guests :
export const DAILY_GUEST_REQUEST = 'DAILY_GUEST_REQUEST'
export const DAILY_GUEST_SUCCESS = 'DAILY_GUEST_SUCCESS'
export const DAILY_GUEST_FAILURE = 'DAILY_GUEST_FAILURE'

// daily cancellation :
export const DAILY_CANCELLATION_REQUEST = 'DAILY_CANCELLATION_REQUEST'
export const DAILY_CANCELLATION_SUCCESS = 'DAILY_CANCELLATION_SUCCESS'
export const DAILY_CANCELLATION_FAILURE = 'DAILY_CANCELLATION_FAILURE'

// hourly guests :
export const HOURLY_GUESTS_REQUEST = 'HOURLY_GUESTS_REQUEST';
export const HOURLY_GUESTS_SUCCESS = 'HOURLY_GUESTS_SUCCESS';
export const HOURLY_GUESTS_FAILURE = 'HOURLY_GUESTS_FAILURE';

// daily hourly checkIn :
export const DAILY_HOURLY_CHECKIN_REQUEST = 'DAILY_HOURLY_CHECKIN_REQUEST';
export const DAILY_HOURLY_CHECKIN_SUCCESS = 'DAILY_HOURLY_CHECKIN_SUCCESS';
export const DAILY_HOURLY_CHECKIN_FAILURE = 'DAILY_HOURLY_CHECKIN_FAILURE';

// day over day guest :
export const DAY_OVER_DAY_GUEST_REQUEST = 'DAY_OVER_DAY_GUEST_REQUEST';
export const DAY_OVER_DAY_GUEST_SUCCESS = 'DAY_OVER_DAY_GUEST_SUCCESS';
export const DAY_OVER_DAY_GUEST_FAILURE = 'DAY_OVER_DAY_GUEST_FAILURE';

// peak summary
export const PEAK_SUMMARY_REQUEST = 'PEAK_SUMMARY_REQUEST';
export const PEAK_SUMMARY_SUCCESS = 'PEAK_SUMMARY_SUCCESS';
export const PEAK_SUMMARY_FAILURE = 'PEAK_SUMMARY_FAILURE';

// party size
export const PARTY_SIZE_REQUEST = 'PARTY_SIZE_REQUEST';
export const PARTY_SIZE_SUCCESS = 'PARTY_SIZE_SUCCESS';
export const PARTY_SIZE_FAILURE = 'PARTY_SIZE_FAILURE';

// customer size
export const CUSTOMER_SIZE_REQUEST = 'CUSTOMER_SIZE_REQUEST';
export const CUSTOMER_SIZE_SUCCESS = 'CUSTOMER_SIZE_SUCCESS';
export const CUSTOMER_SIZE_FAILURE = 'CUSTOMER_SIZE_FAILURE';

// new customer size
export const NEW_CUSTOMER_SIZE_REQUEST = 'NEW_CUSTOMER_SIZE_REQUEST'
export const NEW_CUSTOMER_SIZE_SUCCESS = 'NEW_CUSTOMER_SIZE_SUCCESS'
export const NEW_CUSTOMER_SIZE_FAILURE = 'NEW_CUSTOMER_SIZE_FAILURE'

// customer details
export const CUSTOMER_DETAILS_REQUEST = 'CUSTOMER_DETAILS_REQUEST';
export const CUSTOMER_DETAILS_SUCCESS = 'CUSTOMER_DETAILS_SUCCESS';
export const CUSTOMER_DETAILS_FAILURE = 'CUSTOMER_DETAILS_FAILURE';

// live check-in status
export const LIVE_CHECKIN_STATUS_REQUEST = 'LIVE_CHECKIN_STATUS_REQUEST';
export const LIVE_CHECKIN_STATUS_SUCCESS = 'LIVE_CHECKIN_STATUS_SUCCESS';
export const LIVE_CHECKIN_STATUS_FAILURE = 'LIVE_CHECKIN_STATUS_FAILURE';

// daily CheckIn Status
export const DAILY_CHECKIN_STATUS_REQUEST = 'DAILY_CHECKIN_STATUS_REQUEST';
export const DAILY_CHECKIN_STATUS_SUCCESS = 'DAILY_CHECKIN_STATUS_SUCCESS';
export const DAILY_CHECKIN_STATUS_FAILURE = 'DAILY_CHECKIN_STATUS_FAILURE';










