export const OFFER_LIST_REQUEST = "OFFER_LIST_REQUEST";
export const OFFER_LIST_SUCCESS = "OFFER_LIST_SUCCESS";
export const OFFER_LIST_FAILURE = "OFFER_LIST_FAILURE";


export const DROPDOWN_DATA_REQUEST = "DROPDOWN_DATA_REQUEST";
export const DROPDOWN_DATA_SUCCESS = "DROPDOWN_DATA_SUCCESS";
export const DROPDOWN_DATA_FAILURE = "DROPDOWN_DATA_FAILURE";

export const CREATE_OFFER_REQUEST ="CREATE_OFFER_REQUEST";
export const CREATE_OFFER_SUCCESS = "CREATE_OFFER_SUCCESS";
export const CREATE_OFFER_FAILURE = "CREATE_OFFER_FAILURE";
export const CLEAR_OFFER_SUCCESS = "CLEAR_OFFER_SUCCESS";

export const EDIT_OFFER_REQUEST ="EDIT_OFFER_REQUEST";
export const EDIT_OFFER_SUCCESS = "EDIT_OFFER_SUCCESS";
export const EDIT_OFFER_FAILURE = "EDIT_OFFER_FAILURE";


export const OFFER_REMOVE_ITEM = "OFFER_REMOVE_ITEM";
export const OFFER_REMOVE_ITEM_SUCCESS = "OFFER_REMOVE_ITEM_SUCCESS";
export const OFFER_DISABLE_ITEM_SUCCESS = "OFFER_DISABLE_ITEM_SUCCESS";


export const OFFER_DELETE_REQUEST = "OFFER_DELETE_REQUEST";
export const OFFER_DISABLE_REQUEST = "OFFER_DISABLE_REQUEST";
export const OFFER_DELETE_SUCCESS = "OFFER_DELETE_SUCCESS";
export const OFFER_DISABLE_SUCCESS = "OFFER_DISABLE_SUCCESS";

export const SET_OFFER_STATUS = "SET_OFFER_STATUS";