export const SALES_TRENDS_REQUEST = 'SALES_TRENDS_REQUEST';
export const SALES_TRENDS_SUCCESS = 'SALES_TRENDS_SUCCESS';
export const SALES_TRENDS_FAILURE = 'SALES_TRENDS_FAILURE';


export const CATEGORIES_LEVEL_SALES_TREND_REQUEST = 'CATEGORIES_LEVEL_SALES_TREND_REQUEST';
export const CATEGORIES_LEVEL_SALES_TREND_SUCCESS = 'CATEGORIES_LEVEL_SALES_TREND_SUCCESS';
export const CATEGORIES_LEVEL_SALES_TREND_FAILURE = 'CATEGORIES_LEVEL_SALES_TREND_FAILURE';


export const ITEMS_LEVEL_SALES_TREND_REQUEST = 'ITEMS_LEVEL_SALES_TREND_REQUEST';
export const ITEMS_LEVEL_SALES_TREND_SUCCESS = 'ITEMS_LEVEL_SALES_TREND_SUCCESS';
export const ITEMS_LEVEL_SALES_TREND_FAILURE = 'ITEMS_LEVEL_SALES_TREND_FAILURE';

